# -*- coding: utf-8 -*-
"""TTSS_customer04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdeX82To-kYFucoF9bZUZZT5eJP23edT
"""

!pip install torchgpipe

from google.colab import drive
import torch, os, time, torchvision, json, gc
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torchgpipe import GPipe
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

# 1. KIỂM TRA GPU TRƯỚC KHI CHẠY
if not torch.cuda.is_available():
    print("❌ LỖI NGHIÊM TRỌNG: GPU CHƯA ĐƯỢC BẬT!")
    print("Vào Runtime -> Change runtime type -> Chọn T4 GPU rồi chạy lại cell này.")
else:
    print(f"✅ GPU SẴN SÀNG: {torch.cuda.get_device_name(0)}")

# 2. Kết nối Google Drive
drive.mount('/content/drive')

# 3. Định nghĩa đường dẫn
BASE_PATH = "/content/drive/MyDrive/NTT"
if not os.path.exists(BASE_PATH):
    os.makedirs(BASE_PATH)

PATH_STD = os.path.join(BASE_PATH, "model_standard.pth")
PATH_GPIPE = os.path.join(BASE_PATH, "model_gpipe.pth")
LOG_FILE = os.path.join(BASE_PATH, "experiment_results.json")

# 4. Tham số thực nghiệm
BATCH_SIZE = 16
MICRO_BATCHES = 4
EPOCHS = 5

def get_data():
    t = transforms.Compose([
        transforms.Resize(224),
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
    ])
    ds = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=t)
    # pin_memory chỉ True khi có GPU
    return torch.utils.data.DataLoader(
        ds,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=0,
        pin_memory=torch.cuda.is_available()
    )

# 5. Khởi tạo hoặc nạp Log File
if os.path.exists(LOG_FILE):
    try:
        with open(LOG_FILE, 'r') as f:
            res_data = json.load(f)
        for mode in ["std", "gpipe"]:
            if "loss_history" not in res_data[mode]: res_data[mode]["loss_history"] = []
            if "acc_history" not in res_data[mode]: res_data[mode]["acc_history"] = []
        print("✅ Đã nạp Log File thành công.")
    except Exception as e:
        print(f"⚠️ Lỗi đọc Log: {e}")
        res_data = None

if not os.path.exists(LOG_FILE) or res_data is None:
    res_data = {
        "std": {"vram": 0.0, "time": 0.0, "epoch": 0, "loss_history": [], "acc_history": []},
        "gpipe": {"vram": 0.0, "time": 0.0, "epoch": 0, "loss_history": [], "acc_history": []}
    }
    print("🚀 Khởi tạo cấu trúc log mới.")

print("\n>>> ĐANG CHẠY CHẾ ĐỘ: STANDARD")
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    try: torch.cuda.reset_peak_memory_stats(device)
    except: pass

model = torchvision.models.resnet101(num_classes=10).to(device)
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
criterion = nn.CrossEntropyLoss()
curr_epoch = res_data["std"]["epoch"]

if os.path.exists(PATH_STD):
    try:
        ckpt = torch.load(PATH_STD, map_location=device)
        model.load_state_dict(ckpt['model'])
        optimizer.load_state_dict(ckpt['optimizer'])
        print(f"✅ Resume Standard từ Epoch {curr_epoch}")
    except Exception as e: print(f"⚠️ Lỗi Resume: {e}")

try:
    if curr_epoch < EPOCHS:
        loader = get_data()
        for epoch in range(curr_epoch, EPOCHS):
            start_t = time.time()
            model.train()
            running_loss, correct, total = 0.0, 0, 0

            pbar = tqdm(loader, desc=f"Standard Epoch {epoch+1}/{EPOCHS}")
            for inputs, labels in pbar:
                inputs, labels = inputs.to(device), labels.to(device)
                optimizer.zero_grad()
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()

                running_loss += loss.item()
                _, predicted = outputs.max(1)
                total += labels.size(0)
                correct += predicted.eq(labels).sum().item()
                pbar.set_postfix(loss=running_loss/(pbar.n+1), acc=100.*correct/total)

            # Lưu nhật ký epoch
            res_data["std"]["time"] += (time.time() - start_t)
            if torch.cuda.is_available():
                res_data["std"]["vram"] = max(res_data["std"]["vram"], torch.cuda.max_memory_allocated(device) / 1024**2)

            res_data["std"]["loss_history"].append(running_loss / len(loader))
            res_data["std"]["acc_history"].append(100. * correct / total)
            res_data["std"]["epoch"] = epoch + 1

            torch.save({'model': model.state_dict(), 'optimizer': optimizer.state_dict()}, PATH_STD)
            with open(LOG_FILE, 'w') as f: json.dump(res_data, f)

    print(f"✅ Xong Standard. Peak VRAM: {res_data['std']['vram']:.2f} MB")
finally:
    del model, optimizer; gc.collect(); torch.cuda.empty_cache()

print("\n>>> ĐANG CHẠY CHẾ ĐỘ: GPIPE")
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    try: torch.cuda.reset_peak_memory_stats(device)
    except: pass

original = torchvision.models.resnet101(num_classes=10)
layers = nn.Sequential(
    nn.Sequential(original.conv1, original.bn1, original.relu, original.maxpool, original.layer1, original.layer2),
    nn.Sequential(original.layer3, original.layer4, original.avgpool, nn.Flatten(), original.fc)
)

model_gp = GPipe(layers, balance=[1, 1], devices=[device]*2, chunks=MICRO_BATCHES, checkpoint='always')
optimizer = optim.SGD(model_gp.parameters(), lr=0.01, momentum=0.9)
criterion = nn.CrossEntropyLoss()
curr_epoch = res_data["gpipe"]["epoch"]

if os.path.exists(PATH_GPIPE):
    try:
        ckpt = torch.load(PATH_GPIPE, map_location=device)
        model_gp.load_state_dict(ckpt['model'])
        optimizer.load_state_dict(ckpt['optimizer'])
        print(f"✅ Resume GPipe từ Epoch {curr_epoch}")
    except Exception as e: print(f"⚠️ Lỗi Resume: {e}")

try:
    if curr_epoch < EPOCHS:
        loader = get_data()
        for epoch in range(curr_epoch, EPOCHS):
            start_t = time.time()
            model_gp.train()
            running_loss, correct, total = 0.0, 0, 0

            pbar = tqdm(loader, desc=f"GPipe Epoch {epoch+1}/{EPOCHS}")
            for inputs, labels in pbar:
                inputs, labels = inputs.to(device), labels.to(device)
                optimizer.zero_grad()
                outputs = model_gp(inputs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()

                running_loss += loss.item()
                _, predicted = outputs.max(1)
                total += labels.size(0)
                correct += predicted.eq(labels).sum().item()
                pbar.set_postfix(loss=running_loss/(pbar.n+1), acc=100.*correct/total)

            res_data["gpipe"]["time"] += (time.time() - start_t)
            if torch.cuda.is_available():
                res_data["gpipe"]["vram"] = max(res_data["gpipe"]["vram"], torch.cuda.max_memory_allocated(device) / 1024**2)

            res_data["gpipe"]["loss_history"].append(running_loss / len(loader))
            res_data["gpipe"]["acc_history"].append(100. * correct / total)
            res_data["gpipe"]["epoch"] = epoch + 1

            torch.save({'model': model_gp.state_dict(), 'optimizer': optimizer.state_dict()}, PATH_GPIPE)
            with open(LOG_FILE, 'w') as f: json.dump(res_data, f)

    print(f"✅ Xong GPipe. Peak VRAM: {res_data['gpipe']['vram']:.2f} MB")
finally:
    del model_gp, optimizer; gc.collect(); torch.cuda.empty_cache()

import pandas as pd

# 1. Tính toán lại chỉ số
s_v, g_v = res_data["std"]["vram"], res_data["gpipe"]["vram"]
s_t, g_t = res_data["std"]["time"], res_data["gpipe"]["time"]

results_table = {
    "Speedup (T_std / T_gp)": s_t / g_t if g_t > 0 else 0,
    "Efficiency (Speedup / K=2)": (s_t / g_t) / 2 if g_t > 0 else 0,
    "Memory Savings (%)": ((s_v - g_v) / s_v * 100) if s_v > 0 else 0,
    "Re-computation Overhead (%)": ((g_t - s_t) / s_t * 100) if s_t > 0 else 0
}

# 2. In bảng kết quả định dạng Markdown (để copy thẳng vào Word)
print(f"| {'CHỈ SỐ HIỆU NĂNG':<30} | {'GIÁ TRỊ':<15} |")
print(f"|{'-'*32}|{'-'*17}|")
for k, v in results_table.items():
    print(f"| {k:<30} | {v:<15.4f} |")

# 3. Vẽ biểu đồ (Đã sửa lỗi palette và legend)
plt.style.use('seaborn-v0_8-muted')
fig, axes = plt.subplots(2, 2, figsize=(18, 12))

# Chart 1: VRAM (Bar) - Cập nhật fix Warning
df_vram = pd.DataFrame({'Mode': ['Standard', 'GPipe'], 'VRAM (MB)': [s_v, g_v]})
sns.barplot(data=df_vram, x='Mode', y='VRAM (MB)', hue='Mode', ax=axes[0,0], palette='magma', legend=False)
axes[0,0].set_title('Peak VRAM Usage (MB) - Lower is Better', fontsize=14, fontweight='bold')
axes[0,0].set_ylabel('Memory (MB)')

# Chart 2: Metrics (Bar) - Cập nhật fix Warning
metric_names = list(results_table.keys())[:2]
metric_values = list(results_table.values())[:2]
df_metrics = pd.DataFrame({'Metric': metric_names, 'Value': metric_values})
sns.barplot(data=df_metrics, x='Metric', y='Value', hue='Metric', ax=axes[0,1], palette='viridis', legend=False)
axes[0,1].set_title('Speedup & Efficiency (K=2 GPUs)', fontsize=14, fontweight='bold')
axes[0,1].set_ylim(0, 1.2) # Giới hạn 1.2 để dễ nhìn Speedup

# Chart 3: Loss Convergence (Line)
axes[1,0].plot(res_data["std"]["loss_history"], label='Standard', marker='o', color='#3498db', linewidth=2.5)
axes[1,0].plot(res_data["gpipe"]["loss_history"], label='GPipe', marker='s', color='#e74c3c', linestyle='--', linewidth=2.5)
axes[1,0].set_title('Training Loss Convergence', fontsize=14, fontweight='bold')
axes[1,0].set_xlabel('Epoch'); axes[1,0].set_ylabel('Loss Value')
axes[1,0].legend(frameon=True, fontsize=12)

# Chart 4: Accuracy History (Line)
axes[1,1].plot(res_data["std"]["acc_history"], label='Standard', marker='o', color='#2ecc71', linewidth=2.5)
axes[1,1].plot(res_data["gpipe"]["acc_history"], label='GPipe', marker='s', color='#9b59b6', linestyle='--', linewidth=2.5)
axes[1,1].set_title('Top-1 Accuracy History (%)', fontsize=14, fontweight='bold')
axes[1,1].set_xlabel('Epoch'); axes[1,1].set_ylabel('Accuracy (%)')
axes[1,1].legend(frameon=True, fontsize=12)

plt.suptitle(f"GPipe Performance Analysis - ResNet-101 (BS={BATCH_SIZE}, Micro-batches={MICRO_BATCHES})", fontsize=18, fontweight='bold', y=1.02)
plt.tight_layout()

# Tự động lưu ảnh để cho vào luận văn
plt.savefig(os.path.join(BASE_PATH, "gpipe_evaluation_charts.png"), dpi=300, bbox_inches='tight')
plt.show()

from IPython.display import display, HTML

# 1. Chuẩn bị dữ liệu Performance
s_v, g_v = res_data["std"]["vram"], res_data["gpipe"]["vram"]
s_t, g_t = res_data["std"]["time"], res_data["gpipe"]["time"]
num_epochs = min(len(res_data["std"]["loss_history"]), len(res_data["gpipe"]["loss_history"]))

# 2. Tạo bảng So sánh Hiệu năng
html_perf = f"""
<h3>Bảng 1: So sánh hiệu năng hệ thống</h3>
<table border="1" style="border-collapse: collapse; width: 100%; font-family: Arial; text-align: center;">
  <tr style="background-color: #34495e; color: white;">
    <th>Chỉ số đánh giá</th>
    <th>Standard (1 GPU)</th>
    <th>GPipe (2 GPUs)</th>
    <th>Chênh lệch (%)</th>
  </tr>
  <tr>
    <td>Peak VRAM (MB)</td>
    <td>{s_v:.2f}</td>
    <td>{g_v:.2f}</td>
    <td style="color: green; font-weight: bold;">{((g_v-s_v)/s_v*100):.2f}%</td>
  </tr>
  <tr>
    <td>Total Time (s)</td>
    <td>{s_t:.2f}</td>
    <td>{g_t:.2f}</td>
    <td style="color: red;">+{((g_t-s_t)/s_t*100):.2f}%</td>
  </tr>
</table>
"""

# 3. Tạo bảng Chi tiết Hội tụ
rows_conv = ""
for i in range(num_epochs):
    sl, gl = res_data["std"]["loss_history"][i], res_data["gpipe"]["loss_history"][i]
    sa, ga = res_data["std"]["acc_history"][i], res_data["gpipe"]["acc_history"][i]
    rows_conv += f"""
    <tr>
      <td>{i+1}</td>
      <td>{sl:.4f}</td>
      <td>{gl:.4f}</td>
      <td>{sa:.2f}%</td>
      <td>{ga:.2f}%</td>
      <td>{abs(sl-gl):.6f}</td>
    </tr>"""

html_conv = f"""
<br><h3>Bảng 2: Chi tiết quá trình hội tụ qua các Epoch</h3>
<table border="1" style="border-collapse: collapse; width: 100%; font-family: Arial; text-align: center;">
  <tr style="background-color: #2980b9; color: white;">
    <th>Epoch</th>
    <th>Std Loss</th>
    <th>GPipe Loss</th>
    <th>Std Acc</th>
    <th>GPipe Acc</th>
    <th>Delta Loss (Δ)</th>
  </tr>
  {rows_conv}
</table>
"""

display(HTML(html_perf + html_conv))